version: '1.0'
services:
  db:
    image: postgres
    restart: always
    env_file:
      -.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      -5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/seed.sql
  
  backend:
    build: .
    ports:
      -3000:3000
    env_file:
      - .env
    depends_on:
      - db
    

  volumes:
    - db_data
  
  
