version: "3"
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    volumes:
      - ./scripts/seed.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    image: tsapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      API_PORT: ${API_PORT}
      JWT_KEY: ${JWT_KEY}
      ALPHA: ${ALPHA}
